/**
 * build-form-v3-ar.gs  —  ARABIC-ONLY, GENERATED by instrument_v3.py. Do not edit by hand; edit the .py and regenerate.
 *
 * Builds the Arabic-only Google Form (no language picker).
 * HOW TO RUN: script.google.com -> New project -> paste -> Run buildFormArabic -> approve -> read Execution log.
 *
 * AFTER BUILDING, BY HAND:
 *   1. Settings: Collect email OFF; Limit to 1 response OFF; Allow response editing OFF;
 *      "Restrict to users in <organisation>" OFF.
 *   2. Optional: Shuffle row order inside grids only.
 *   3. TEST on a phone: consent "No" -> form ends; eligibility "No" -> form ends; 7 pages in total;
 *      every grid shows 5 columns without sideways scrolling; last page -> submits.
 *   4. Pilot in a COPY of the form (File -> Make a copy). Never pilot in the live form.
 */

var DATA = [
 {
  "id": "consent",
  "title_en": "About this survey",
  "title_ar": "عن هذا الاستبيان",
  "items": [
   {
    "code": null,
    "type": "text",
    "q_en": "About this survey",
    "q_ar": "عن هذا الاستبيان",
    "help_en": "This survey is part of a master's research project at the Lebanese University and takes about 7 minutes. Taking part is voluntary and anonymous: no names or contact details are collected, so a response cannot be withdrawn once submitted. Answers are used for research only and reported as group results.",
    "help_ar": "هذا الاستبيان جزء من مشروع بحثي لدرجة الماجستير في الجامعة اللبنانية، ويستغرق نحو 7 دقائق. المشاركة طوعية ومجهولة الهوية: لا نجمع أي أسماء أو بيانات اتصال، لذلك لا يمكن سحب الإجابة بعد إرسالها. تُستخدم الإجابات لأغراض بحثية فقط، وتُعرض النتائج بشكل إجمالي.",
    "opts_en": [],
    "opts_ar": [],
    "rows": [],
    "route": null
   },
   {
    "code": "Consent",
    "type": "gate",
    "q_en": "I am 18 or older and I agree to take part.",
    "q_ar": "عمري 18 عاماً أو أكثر، وأوافق على المشاركة.",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "I agree",
     "I do not agree"
    ],
    "opts_ar": [
     "أوافق",
     "لا أوافق"
    ],
    "rows": [],
    "route": null
   }
  ]
 },
 {
  "id": "elig",
  "title_en": "Who can take part",
  "title_ar": "من يمكنه المشاركة",
  "items": [
   {
    "code": "Eligible",
    "type": "gate",
    "q_en": "Do ALL of these apply to you?\n• Arabic is your first language\n• You also use English for study or work\n• You have used AI tools (such as ChatGPT, Gemini or Claude) at least weekly for 6 months or more",
    "q_ar": "هل تنطبق عليك كل ما يلي؟\n• العربية لغتك الأولى\n• تستخدم الإنجليزية أيضاً في الدراسة أو العمل\n• تستخدم أدوات الذكاء الاصطناعي (مثل شات جي بي تي أو جيميني أو كلود) مرة أسبوعياً على الأقل منذ ستة أشهر أو أكثر",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Yes",
     "No"
    ],
    "opts_ar": [
     "نعم",
     "لا"
    ],
    "rows": [],
    "route": null
   }
  ]
 },
 {
  "id": "you",
  "title_en": "About you",
  "title_ar": "معلومات عنك",
  "items": [
   {
    "code": "Role",
    "type": "mc",
    "q_en": "You are currently…",
    "q_ar": "أنت حالياً…",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "A student",
     "Employed",
     "Both",
     "Neither"
    ],
    "opts_ar": [
     "طالب",
     "موظف",
     "طالب وموظف",
     "غير ذلك"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Education",
    "type": "mc",
    "q_en": "Education level (completed or in progress)",
    "q_ar": "المستوى التعليمي (مكتمل أو قيد الدراسة)",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Secondary",
     "Bachelor's",
     "Master's or higher"
    ],
    "opts_ar": [
     "ثانوي",
     "بكالوريوس",
     "ماجستير أو أعلى"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Field",
    "type": "mc",
    "q_en": "Field of study or work",
    "q_ar": "مجال الدراسة أو العمل",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Computing / IT",
     "Engineering",
     "Sciences or health",
     "Business",
     "Humanities, education or law",
     "Other"
    ],
    "opts_ar": [
     "الحوسبة / تقنية المعلومات",
     "الهندسة",
     "العلوم أو الصحة",
     "إدارة الأعمال",
     "العلوم الإنسانية أو التربية أو القانون",
     "غير ذلك"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Age",
    "type": "mc",
    "q_en": "Age",
    "q_ar": "العمر",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Under 25",
     "25 to 34",
     "35 to 44",
     "45 or over"
    ],
    "opts_ar": [
     "أقل من 25",
     "من 25 إلى 34",
     "من 35 إلى 44",
     "45 فأكثر"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Gender",
    "type": "mc",
    "q_en": "Gender",
    "q_ar": "الجنس",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Female",
     "Male",
     "Prefer not to say"
    ],
    "opts_ar": [
     "أنثى",
     "ذكر",
     "أفضّل عدم الإجابة"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Country_GrewUp",
    "type": "mc",
    "q_en": "Where did you grow up?",
    "q_ar": "أين نشأت؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Lebanon",
     "Syria, Jordan or Palestine",
     "The Gulf",
     "Egypt or North Africa",
     "Another Arab country",
     "Outside the Arab world"
    ],
    "opts_ar": [
     "لبنان",
     "سوريا أو الأردن أو فلسطين",
     "الخليج",
     "مصر أو شمال أفريقيا",
     "بلد عربي آخر",
     "خارج العالم العربي"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Country_Now",
    "type": "mc",
    "q_en": "Where do you live now?",
    "q_ar": "أين تعيش الآن؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Lebanon",
     "Syria, Jordan or Palestine",
     "The Gulf",
     "Egypt or North Africa",
     "Another Arab country",
     "Outside the Arab world"
    ],
    "opts_ar": [
     "لبنان",
     "سوريا أو الأردن أو فلسطين",
     "الخليج",
     "مصر أو شمال أفريقيا",
     "بلد عربي آخر",
     "خارج العالم العربي"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Moved_Since2022",
    "type": "mc",
    "q_en": "Have you moved to another country since 2022?",
    "q_ar": "هل انتقلت للعيش في بلد آخر منذ عام 2022؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Yes",
     "No"
    ],
    "opts_ar": [
     "نعم",
     "لا"
    ],
    "rows": [],
    "route": null
   }
  ]
 },
 {
  "id": "ai",
  "title_en": "Your use of AI tools",
  "title_ar": "استخدامك لأدوات الذكاء الاصطناعي",
  "items": [
   {
    "code": "AI_Start",
    "type": "mc",
    "q_en": "When did you start using AI tools regularly (at least weekly)?",
    "q_ar": "متى بدأت باستخدام أدوات الذكاء الاصطناعي بانتظام (مرة أسبوعياً على الأقل)؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "2022 or earlier",
     "2023",
     "2024",
     "2025",
     "2026"
    ],
    "opts_ar": [
     "2022 أو قبل ذلك",
     "2023",
     "2024",
     "2025",
     "2026"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "AI_Freq",
    "type": "mc",
    "q_en": "How often do you use AI tools?",
    "q_ar": "كم مرة تستخدم أدوات الذكاء الاصطناعي؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Once a week",
     "A few days a week",
     "Once a day",
     "Several times a day"
    ],
    "opts_ar": [
     "مرة في الأسبوع",
     "بضعة أيام في الأسبوع",
     "مرة في اليوم",
     "عدة مرات في اليوم"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "AI_TaskShare",
    "type": "mc",
    "q_en": "How much of your work or study do you do with the help of AI?",
    "q_ar": "كم من عملك أو دراستك تنجزه بمساعدة الذكاء الاصطناعي؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Very little",
     "Some",
     "About half",
     "Most",
     "Almost all"
    ],
    "opts_ar": [
     "القليل جداً",
     "بعضه",
     "نحو النصف",
     "معظمه",
     "كله تقريباً"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "AI_Breadth",
    "type": "check",
    "q_en": "What do you use AI for? (tick all that apply)",
    "q_ar": "فيمَ تستخدم الذكاء الاصطناعي؟ (اختر كل ما ينطبق)",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Writing or editing",
     "Coding",
     "Searching for information",
     "Translation",
     "Studying",
     "Emails and messages",
     "Ideas",
     "Personal advice"
    ],
    "opts_ar": [
     "الكتابة أو التحرير",
     "البرمجة",
     "البحث عن معلومات",
     "الترجمة",
     "الدراسة",
     "البريد والرسائل",
     "توليد الأفكار",
     "نصائح شخصية"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "AI_Lang",
    "type": "mc",
    "q_en": "In which language do you usually write to AI?",
    "q_ar": "بأي لغة تكتب للذكاء الاصطناعي عادةً؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Always Arabic",
     "Mostly Arabic",
     "Both equally",
     "Mostly English",
     "Always English",
     "Another language"
    ],
    "opts_ar": [
     "العربية دائماً",
     "العربية غالباً",
     "الاثنتان بالتساوي",
     "الإنجليزية غالباً",
     "الإنجليزية دائماً",
     "لغة أخرى"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "AI_Content",
    "type": "mc",
    "q_en": "How often do you come across AI-generated content (videos, voice-overs, summaries in search results)?",
    "q_ar": "كم تصادف محتوى مولّداً بالذكاء الاصطناعي (فيديوهات، تعليق صوتي، ملخّصات في نتائج البحث)؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Never",
     "Rarely",
     "Sometimes",
     "Often",
     "Every day"
    ],
    "opts_ar": [
     "لا أصادفه",
     "نادراً",
     "أحياناً",
     "كثيراً",
     "يومياً"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "AI_ContentLang",
    "type": "mc",
    "q_en": "When the same content is available in AI-generated Arabic voice and in the original English, which do you usually choose?",
    "q_ar": "عندما يتوفّر المحتوى نفسه بصوت عربي مولّد بالذكاء الاصطناعي وبالإنجليزية الأصلية، ماذا تختار عادةً؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Always Arabic",
     "Mostly Arabic",
     "Depends on the topic",
     "Mostly English",
     "Always English"
    ],
    "opts_ar": [
     "العربية دائماً",
     "العربية غالباً",
     "بحسب الموضوع",
     "الإنجليزية غالباً",
     "الإنجليزية دائماً"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Events",
    "type": "check",
    "q_en": "Since you started using AI regularly, did any of these also happen? (tick all that apply)",
    "q_ar": "منذ أن بدأت باستخدام الذكاء الاصطناعي بانتظام، هل حدث لك أيضاً أيٌّ مما يلي؟ (اختر كل ما ينطبق)",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Started university",
     "Graduated",
     "New job",
     "Started studying or working in English",
     "Moved to another country",
     "None of these"
    ],
    "opts_ar": [
     "بدأت الجامعة",
     "تخرّجت",
     "بدأت عملاً جديداً",
     "بدأت الدراسة أو العمل بالإنجليزية",
     "انتقلت إلى بلد آخر",
     "لا شيء مما سبق"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "FushaPreAI",
    "type": "mc",
    "q_en": "Before using AI, did you write in Fusha (assignments, exams, official letters)?",
    "q_ar": "قبل استخدامك للذكاء الاصطناعي، هل كنت تكتب بالفصحى (واجبات، امتحانات، رسائل رسمية)؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Yes, regularly",
     "Sometimes",
     "No"
    ],
    "opts_ar": [
     "نعم، بانتظام",
     "أحياناً",
     "لا"
    ],
    "rows": [],
    "route": null
   }
  ]
 },
 {
  "id": "cur",
  "title_en": "Your languages today",
  "title_ar": "لغاتك اليوم",
  "items": [
   {
    "code": "CurUse",
    "type": "grid",
    "q_en": "These days, which language do you mostly use for each of these?",
    "q_ar": "هذه الأيام، ما اللغة التي تستخدمها غالباً في كلٍّ مما يلي؟",
    "help_en": "Arabic means your dialect or Fusha.",
    "help_ar": "نقصد بالعربية: لهجتك أو الفصحى.",
    "opts_en": [
     "Mostly Arabic",
     "Arabic and English",
     "Mostly English",
     "Another language",
     "Not applicable"
    ],
    "opts_ar": [
     "العربية غالباً",
     "العربية والإنجليزية",
     "الإنجليزية غالباً",
     "لغة أخرى",
     "لا ينطبق"
    ],
    "rows": [
     {
      "code": "CurUse_WorkStudy",
      "en": "Work or studies",
      "ar": "العمل أو الدراسة"
     },
     {
      "code": "CurUse_Writing",
      "en": "Writing messages and posts",
      "ar": "كتابة الرسائل والمنشورات"
     },
     {
      "code": "CurUse_Self",
      "en": "Talking to myself or writing my own notes",
      "ar": "التحدث مع نفسي أو كتابة ملاحظاتي الخاصة"
     },
     {
      "code": "CurUse_Personal",
      "en": "Personal matters",
      "ar": "الأمور الشخصية"
     },
     {
      "code": "CurUse_Family",
      "en": "With my family or friends",
      "ar": "مع العائلة أو الأصدقاء"
     },
     {
      "code": "CurUse_Religion",
      "en": "Religious texts",
      "ar": "النصوص الدينية"
     },
     {
      "code": "CurUse_Formal",
      "en": "Reading or writing formal texts (news, documents, articles)",
      "ar": "قراءة أو كتابة نصوص رسمية (أخبار، وثائق، مقالات)"
     },
     {
      "code": "CurUse_Consume",
      "en": "Following content (videos, articles)",
      "ar": "متابعة المحتوى (فيديوهات، مقالات)"
     }
    ],
    "route": null
   }
  ]
 },
 {
  "id": "change",
  "title_en": "Has AI changed your Arabic?",
  "title_ar": "هل غيّر الذكاء الاصطناعي عربيتك؟",
  "items": [
   {
    "code": null,
    "type": "text",
    "q_en": "",
    "q_ar": "",
    "help_en": "On this page we ask whether AI has changed how you use Arabic.\n• Compare now with before you started using AI regularly.\n• Mixing Arabic and English is normal.",
    "help_ar": "في هذه الصفحة نسألك: هل غيّر الذكاء الاصطناعي طريقة استخدامك للعربية؟\n• قارن بين الآن وما قبل استخدامك المنتظم للذكاء الاصطناعي.\n• خلط العربية بالإنجليزية أمر طبيعي.",
    "opts_en": [],
    "opts_ar": [],
    "rows": [],
    "route": null
   },
   {
    "code": "ArUse",
    "type": "grid",
    "q_en": "Because of AI, do you now do each of these less or more?",
    "q_ar": "بسبب الذكاء الاصطناعي، هل أصبحت تقوم بكلٍّ مما يلي أقل أم أكثر؟",
    "help_en": "Compare now with before you started using AI regularly.",
    "help_ar": "قارن بين الآن وما قبل استخدامك المنتظم للذكاء الاصطناعي.",
    "opts_en": [
     "Much less",
     "Less",
     "No change",
     "More",
     "Much more"
    ],
    "opts_ar": [
     "أقل بكثير",
     "أقل",
     "لم يتغيّر",
     "أكثر",
     "أكثر بكثير"
    ],
    "rows": [
     {
      "code": "ArUse_WorkStudy",
      "en": "Using Arabic in my work or studies",
      "ar": "استخدام العربية في عملي أو دراستي"
     },
     {
      "code": "ArUse_Writing",
      "en": "Writing messages or posts in Arabic",
      "ar": "كتابة الرسائل أو المنشورات بالعربية"
     },
     {
      "code": "ArUse_Self",
      "en": "Using Arabic when I talk to myself or write my own notes",
      "ar": "استخدام العربية عندما أحدّث نفسي أو أكتب ملاحظاتي الخاصة"
     },
     {
      "code": "ArUse_Personal",
      "en": "Using Arabic for personal matters",
      "ar": "استخدام العربية في الحديث عن أموري الشخصية"
     },
     {
      "code": "ArUse_Family",
      "en": "Using Arabic with my family or friends",
      "ar": "استخدام العربية مع عائلتي أو أصدقائي"
     },
     {
      "code": "ArUse_Fusha",
      "en": "Reading or writing Fusha (news, documents, articles)",
      "ar": "قراءة الفصحى أو كتابتها (أخبار، وثائق، مقالات)"
     },
     {
      "code": "ArUse_Religion",
      "en": "Reading or listening to religious texts",
      "ar": "قراءة نصوص دينية أو الاستماع إليها"
     },
     {
      "code": "ArUse_Consume",
      "en": "Following content in Arabic (videos, articles)",
      "ar": "متابعة محتوى بالعربية (فيديوهات، مقالات)"
     },
     {
      "code": "Switch_Mode",
      "en": "Switching between Arabic and English while working or studying",
      "ar": "التنقّل بين العربية والإنجليزية أثناء العمل أو الدراسة"
     }
    ],
    "route": null
   },
   {
    "code": "SwitchEng",
    "type": "mc",
    "q_en": "Has it happened that you did something in English, although you could have done it in Arabic, because AI helps you better in English?",
    "q_ar": "هل حدث أن أنجزت عملاً بالإنجليزية، مع أنه كان بإمكانك إنجازه بالعربية، لأن الذكاء الاصطناعي يساعدك أفضل بالإنجليزية؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Never",
     "Once or twice",
     "Sometimes",
     "Often",
     "Most of the time"
    ],
    "opts_ar": [
     "لم يحدث",
     "مرة أو مرتين",
     "أحياناً",
     "كثيراً",
     "في معظم الأحيان"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "SocialMedia",
    "type": "mc",
    "q_en": "Over the same period, because of social media, do you now use Arabic less or more?",
    "q_ar": "خلال الفترة نفسها، بسبب وسائل التواصل الاجتماعي، هل أصبحت تستخدم العربية أقل أم أكثر؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Much less",
     "Less",
     "No change",
     "More",
     "Much more"
    ],
    "opts_ar": [
     "أقل بكثير",
     "أقل",
     "لم يتغيّر",
     "أكثر",
     "أكثر بكثير"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Abil",
    "type": "grid",
    "q_en": "Because of AI, has each of these become harder or easier for you, when you use Arabic on your own without AI?",
    "q_ar": "بسبب الذكاء الاصطناعي، هل أصبح كلٌّ مما يلي أصعب أم أسهل عليك، عندما تستخدم العربية بنفسك من دون مساعدته؟",
    "help_en": "Compare now with before you started using AI regularly.",
    "help_ar": "قارن بين الآن وما قبل استخدامك المنتظم للذكاء الاصطناعي.",
    "opts_en": [
     "Much harder",
     "Harder",
     "No change",
     "Easier",
     "Much easier"
    ],
    "opts_ar": [
     "أصعب بكثير",
     "أصعب",
     "لم يتغيّر",
     "أسهل",
     "أسهل بكثير"
    ],
    "rows": [
     {
      "code": "Abil_Lexical",
      "en": "Finding the everyday Arabic word I need",
      "ar": "تذكّر الكلمة العربية اليومية التي أحتاجها"
     },
     {
      "code": "Abil_Fluency",
      "en": "Speaking my dialect smoothly, without pausing for words",
      "ar": "التحدث بلهجتي بطلاقة دون التوقف بحثاً عن الكلمات"
     },
     {
      "code": "Abil_ArabicOnly",
      "en": "Saying what I mean fully in Arabic, without English words",
      "ar": "التعبير عمّا أريده بالعربية كاملاً دون كلمات إنجليزية"
     },
     {
      "code": "Abil_Register",
      "en": "Writing a formal text in Fusha (e.g. a letter or report)",
      "ar": "كتابة نص رسمي بالفصحى (مثل رسالة أو تقرير)"
     }
    ],
    "route": null
   }
  ]
 },
 {
  "id": "views",
  "title_en": "Your views and language background",
  "title_ar": "رأيك وخلفيتك اللغوية",
  "items": [
   {
    "code": "Future",
    "type": "grid",
    "q_en": "In two years, do you think you will use Arabic more or less than you do today for each of these?",
    "q_ar": "برأيك، بعد سنتين، هل ستستخدم العربية في كلٍّ مما يلي أكثر أم أقل مما تستخدمها اليوم؟",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Much less",
     "Less",
     "The same as now",
     "More",
     "Much more"
    ],
    "opts_ar": [
     "أقل بكثير",
     "أقل",
     "كما هي الآن",
     "أكثر",
     "أكثر بكثير"
    ],
    "rows": [
     {
      "code": "Future_WorkStudy",
      "en": "Work or studies",
      "ar": "العمل أو الدراسة"
     },
     {
      "code": "Future_Writing",
      "en": "Writing messages and posts",
      "ar": "كتابة الرسائل والمنشورات"
     },
     {
      "code": "Future_Self",
      "en": "Talking to myself or writing my own notes",
      "ar": "التحدث مع نفسي أو كتابة ملاحظاتي الخاصة"
     },
     {
      "code": "Future_Personal",
      "en": "Personal matters",
      "ar": "الأمور الشخصية"
     },
     {
      "code": "Future_Family",
      "en": "With my family or friends",
      "ar": "مع العائلة أو الأصدقاء"
     },
     {
      "code": "Future_Formal",
      "en": "Reading or writing formal texts",
      "ar": "قراءة أو كتابة نصوص رسمية"
     },
     {
      "code": "Future_Religion",
      "en": "Religious texts",
      "ar": "النصوص الدينية"
     },
     {
      "code": "Future_Consume",
      "en": "Following content (videos, articles)",
      "ar": "متابعة المحتوى (فيديوهات، مقالات)"
     }
    ],
    "route": null
   },
   {
    "code": "Gap",
    "type": "grid",
    "q_en": "How much do you agree?",
    "q_ar": "إلى أي حد توافق على ما يلي؟",
    "help_en": "If you rarely use AI in Arabic, answer from your impression.",
    "help_ar": "إذا كنت نادراً ما تستخدم الذكاء الاصطناعي بالعربية، فأجب بحسب انطباعك.",
    "opts_en": [
     "Strongly disagree",
     "Disagree",
     "Neutral",
     "Agree",
     "Strongly agree"
    ],
    "opts_ar": [
     "أعارض بشدة",
     "أعارض",
     "محايد",
     "أوافق",
     "أوافق بشدة"
    ],
    "rows": [
     {
      "code": "Gap_Understand",
      "en": "AI understands me better in English than in Arabic",
      "ar": "يفهمني الذكاء الاصطناعي بالإنجليزية أفضل من العربية"
     },
     {
      "code": "Gap_Accuracy",
      "en": "AI gives less accurate answers in Arabic than in English",
      "ar": "يعطي الذكاء الاصطناعي إجابات أقل دقة بالعربية منها بالإنجليزية"
     },
     {
      "code": "Gap_Voice",
      "en": "AI-generated Arabic voices and videos sound less natural than English ones",
      "ar": "الأصوات والفيديوهات العربية المولّدة بالذكاء الاصطناعي أقل طبيعية من الإنجليزية"
     },
     {
      "code": "Gap_Equal",
      "en": "AI answers in Arabic are as good as in English (reverse-coded)",
      "ar": "إجابات الذكاء الاصطناعي بالعربية جيدة مثل إجاباته بالإنجليزية"
     }
    ],
    "route": null
   },
   {
    "code": "L1_Home",
    "type": "check",
    "q_en": "Languages spoken at home when you were a child (tick all)",
    "q_ar": "اللغات التي كنت تتحدثها في البيت في طفولتك (اختر كل ما ينطبق)",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Arabic",
     "English",
     "French",
     "Other"
    ],
    "opts_ar": [
     "العربية",
     "الإنجليزية",
     "الفرنسية",
     "غير ذلك"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Sch_SciLang",
    "type": "mc",
    "q_en": "At school, you studied science and maths mostly in…",
    "q_ar": "في المدرسة، درست العلوم والرياضيات غالباً باللغة…",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Arabic",
     "English",
     "French",
     "Other"
    ],
    "opts_ar": [
     "العربية",
     "الإنجليزية",
     "الفرنسية",
     "غير ذلك"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Uni_Lang",
    "type": "mc",
    "q_en": "At university, your courses were mostly in…",
    "q_ar": "في الجامعة، كانت مقرراتك غالباً باللغة…",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Arabic",
     "English",
     "French",
     "Mixed",
     "I did not go to university"
    ],
    "opts_ar": [
     "العربية",
     "الإنجليزية",
     "الفرنسية",
     "مختلطة",
     "لم ألتحق بالجامعة"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Eng_Prof",
    "type": "mc",
    "q_en": "Your English level",
    "q_ar": "مستواك في الإنجليزية",
    "help_en": "",
    "help_ar": "",
    "opts_en": [
     "Weak",
     "Average",
     "Good",
     "Very good",
     "Excellent"
    ],
    "opts_ar": [
     "ضعيف",
     "متوسط",
     "جيد",
     "جيد جداً",
     "ممتاز"
    ],
    "rows": [],
    "route": null
   },
   {
    "code": "Open",
    "type": "para",
    "q_en": "Anything else about how AI has affected your Arabic? (optional)",
    "q_ar": "هل تودّ إضافة أي شيء عن تأثير الذكاء الاصطناعي على عربيتك؟ (اختياري)",
    "help_en": "Please don't mention names of people or places of work.",
    "help_ar": "يُرجى عدم ذكر أسماء أشخاص أو أماكن عمل.",
    "opts_en": [],
    "opts_ar": [],
    "rows": [],
    "route": null
   }
  ]
 }
];
var FORM_AR = {"title": "أدوات الذكاء الاصطناعي واستخدام اللغة في الحياة اليومية", "desc": "استبيان مجهول الهوية يستغرق نحو 7 دقائق، ضمن مشروع بحثي في الجامعة اللبنانية.", "confirm": "شكراً على وقتك."};
var FORM = {"title": "AI tools and everyday language use  |  أدوات الذكاء الاصطناعي واستخدام اللغة في الحياة اليومية", "desc": "About 7 minutes. Anonymous. Choose your language to begin.\nنحو 7 دقائق. مجهول الهوية. اختر لغتك للبدء.", "confirm": "Thank you for your time.  |  شكراً على وقتك.", "picker": "Please choose your language  |  يرجى اختيار لغتك"};

function codeMap_(lang, code, title, i) { Logger.log(['MAP', lang, code, i, title].join(' | ')); }

function chain_(form, lang, skipFirstBreak) {
  var pb = {};        // section id -> PageBreakItem
  var routes = [];    // deferred routing
  var first = null;
  DATA.forEach(function (sec) {
    if (skipFirstBreak && !first) { first = 'page1'; }
    else { var p = form.addPageBreakItem().setTitle(sec['title_' + lang]); pb[sec.id] = p; if (!first) first = p; }
    sec.items.forEach(function (it) {
      var q = it['q_' + lang], h = it['help_' + lang], o = it['opts_' + lang];
      if (it.type === 'text') {
        form.addSectionHeaderItem().setTitle(q || (lang === 'ar' ? 'تعليمات' : 'Instructions')).setHelpText(h);
      } else if (it.type === 'gate') {
        var g = form.addMultipleChoiceItem().setTitle(q).setRequired(true);
        if (h) g.setHelpText(h);
        g.setChoices([g.createChoice(o[0], FormApp.PageNavigationType.CONTINUE),
                      g.createChoice(o[1], FormApp.PageNavigationType.SUBMIT)]);
        codeMap_(lang, it.code, q, 0);
      } else if (it.type === 'mc') {
        var m = form.addMultipleChoiceItem().setTitle(q).setChoiceValues(o).setRequired(true);
        if (h) m.setHelpText(h);
        codeMap_(lang, it.code, q, 0);
      } else if (it.type === 'mc_route') {
        var r = form.addMultipleChoiceItem().setTitle(q).setRequired(true);
        if (h) r.setHelpText(h);
        routes.push({ item: r, it: it, opts: o });
        codeMap_(lang, it.code, q, 0);
      } else if (it.type === 'check') {
        var c = form.addCheckboxItem().setTitle(q).setChoiceValues(o).setRequired(true);
        if (h) c.setHelpText(h);
        codeMap_(lang, it.code, q, 0);
      } else if (it.type === 'grid') {
        var gr = form.addGridItem().setTitle(q)
          .setRows(it.rows.map(function (x) { return x[lang]; })).setColumns(o).setRequired(true);
        if (h) gr.setHelpText(h);
        it.rows.forEach(function (x, i) { codeMap_(lang, x.code, x[lang], i); });
      } else if (it.type === 'para') {
        var pa = form.addParagraphTextItem().setTitle(q).setRequired(false);
        if (h) pa.setHelpText(h);
        codeMap_(lang, it.code, q, 0);
      }
    });
  });
  // wire routing now that every section exists
  var ROUTE_TARGET = { 'A': 'A', 'extra': 'extra', 'WS': 'WS', 'SW': 'SW', 'REG': 'REG', 'D': 'D' };
  routes.forEach(function (rt) {
    var ok = rt.it.route.correct_index, choices = [];
    rt.opts.forEach(function (txt, i) {
      var target = ok.indexOf(i) >= 0 ? rt.it.route.correct_to : rt.it.route.else_to;
      choices.push(rt.item.createChoice(txt, pb[ROUTE_TARGET[target]]));
    });
    rt.item.setChoices(choices);
  });
  return first;
}


function buildFormArabic() {
  var form = FormApp.create(FORM_AR.title);
  form.setTitle(FORM_AR.title).setDescription(FORM_AR.desc)
      .setCollectEmail(false).setLimitOneResponsePerUser(false)
      .setProgressBar(true).setAllowResponseEdits(false)
      .setConfirmationMessage(FORM_AR.confirm);
  chain_(form, 'ar', true);   // consent sits on page 1; every later section gets its own page
  Logger.log('EDIT URL : ' + form.getEditUrl());
  Logger.log('LIVE URL : ' + form.getPublishedUrl());
}
