# -*- coding: utf-8 -*-
"""All questionnaire wording (EN + AR). Edit HERE, then run: python instrument_v3.py"""

S = {
 'change': {'en': ['Much less', 'Less', 'No change', 'More', 'Much more'],
            'ar': ['أقل بكثير', 'أقل', 'لم يتغيّر', 'أكثر', 'أكثر بكثير'],
            'codes': [-2, -1, 0, 1, 2]},
 'easier': {'en': ['Much harder', 'Harder', 'No change', 'Easier', 'Much easier'],
            'ar': ['أصعب بكثير', 'أصعب', 'لم يتغيّر', 'أسهل', 'أسهل بكثير'],
            'codes': [-2, -1, 0, 1, 2]},
 'agree':  {'en': ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
            'ar': ['أعارض بشدة', 'أعارض', 'محايد', 'أوافق', 'أوافق بشدة'],
            'codes': [1, 2, 3, 4, 5]},
 'curuse': {'en': ['Mostly Arabic', 'Arabic and English', 'Mostly English', 'Another language', 'Not applicable'],
            'ar': ['العربية غالباً', 'العربية والإنجليزية', 'الإنجليزية غالباً', 'لغة أخرى', 'لا ينطبق'],
            'codes': [1, 2, 3, 'M4', 'M5']},
 'future': {'en': ['Much less', 'Less', 'The same as now', 'More', 'Much more'],
            'ar': ['أقل بكثير', 'أقل', 'كما هي الآن', 'أكثر', 'أكثر بكثير'],
            'codes': [-2, -1, 0, 1, 2]},
 'rate5':  {'en': ['Very weak', 'Weak', 'Average', 'Good', 'Excellent'],
            'ar': ['ضعيف جداً', 'ضعيف', 'متوسط', 'جيد', 'ممتاز'],
            'codes': [1, 2, 3, 4, 5]},
}

T = {
 'nochange': {'en': "Compare now with before you started using AI regularly.",
              'ar': 'قارن بين الآن وما قبل استخدامك المنتظم للذكاء الاصطناعي.'},
}

SECTIONS = [
 {'id': 'consent', 'title': {'en': 'About this survey', 'ar': 'عن هذا الاستبيان'}, 'items': [
  {'code': None, 'type': 'text',
   'q': {'en': 'About this survey', 'ar': 'عن هذا الاستبيان'},
   'help': {'en': "This survey is part of a master's research project at the Lebanese University and takes about 7 minutes. Taking part is voluntary and anonymous: no names or contact details are collected, so a response cannot be withdrawn once submitted. Answers are used for research only and reported as group results.",
            'ar': 'هذا الاستبيان جزء من مشروع بحثي لدرجة الماجستير في الجامعة اللبنانية، ويستغرق نحو 7 دقائق. المشاركة طوعية ومجهولة الهوية: لا نجمع أي أسماء أو بيانات اتصال، لذلك لا يمكن سحب الإجابة بعد إرسالها. تُستخدم الإجابات لأغراض بحثية فقط، وتُعرض النتائج بشكل إجمالي.'}},
  {'code': 'Consent', 'type': 'gate', 'role': 'screen',
   'q': {'en': 'I am 18 or older and I agree to take part.', 'ar': 'عمري 18 عاماً أو أكثر، وأوافق على المشاركة.'},
   'yes': {'en': 'I agree', 'ar': 'أوافق'}, 'no': {'en': 'I do not agree', 'ar': 'لا أوافق'}},
 ]},
 {'id': 'elig', 'title': {'en': 'Who can take part', 'ar': 'من يمكنه المشاركة'}, 'items': [
  {'code': 'Eligible', 'type': 'gate', 'role': 'screen',
   'q': {'en': 'Do ALL of these apply to you?\n• Arabic is your first language\n• You also use English for study or work\n• You have used AI tools (such as ChatGPT, Gemini or Claude) at least weekly for 6 months or more',
         'ar': 'هل تنطبق عليك كل ما يلي؟\n• العربية لغتك الأولى\n• تستخدم الإنجليزية أيضاً في الدراسة أو العمل\n• تستخدم أدوات الذكاء الاصطناعي (مثل شات جي بي تي أو جيميني أو كلود) مرة أسبوعياً على الأقل منذ ستة أشهر أو أكثر'},
   'yes': {'en': 'Yes', 'ar': 'نعم'}, 'no': {'en': 'No', 'ar': 'لا'}},
 ]},
 {'id': 'you', 'title': {'en': 'About you', 'ar': 'معلومات عنك'}, 'items': [
  {'code': 'Role', 'type': 'mc', 'role': 'descriptive',
   'q': {'en': 'You are currently…', 'ar': 'أنت حالياً…'},
   'o': {'en': ['A student', 'Employed', 'Both', 'Neither'], 'ar': ['طالب', 'موظف', 'طالب وموظف', 'غير ذلك']}},
  {'code': 'Education', 'type': 'mc', 'role': 'covariate (sensitivity) / ML',
   'q': {'en': 'Education level (completed or in progress)', 'ar': 'المستوى التعليمي (مكتمل أو قيد الدراسة)'},
   'o': {'en': ['Secondary', "Bachelor's", "Master's or higher"], 'ar': ['ثانوي', 'بكالوريوس', 'ماجستير أو أعلى']}},
  {'code': 'Field', 'type': 'mc', 'role': 'covariate (computing vs other) / ML',
   'q': {'en': 'Field of study or work', 'ar': 'مجال الدراسة أو العمل'},
   'o': {'en': ['Computing / IT', 'Engineering', 'Sciences or health', 'Business', 'Humanities, education or law', 'Other'],
         'ar': ['الحوسبة / تقنية المعلومات', 'الهندسة', 'العلوم أو الصحة', 'إدارة الأعمال', 'العلوم الإنسانية أو التربية أو القانون', 'غير ذلك']}},
  {'code': 'Age', 'type': 'mc', 'role': 'covariate / ML',
   'q': {'en': 'Age', 'ar': 'العمر'}, 'o': {'en': ['Under 25', '25 to 34', '35 to 44', '45 or over'], 'ar': ['أقل من 25', 'من 25 إلى 34', 'من 35 إلى 44', '45 فأكثر']}},
  {'code': 'Gender', 'type': 'mc', 'role': 'descriptive',
   'q': {'en': 'Gender', 'ar': 'الجنس'}, 'o': {'en': ['Female', 'Male', 'Prefer not to say'], 'ar': ['أنثى', 'ذكر', 'أفضّل عدم الإجابة']}},
  {'code': 'Country_GrewUp', 'type': 'mc', 'role': 'CORE sample rule',
   'q': {'en': 'Where did you grow up?', 'ar': 'أين نشأت؟'},
   'o': {'en': ['Lebanon', 'Syria, Jordan or Palestine', 'The Gulf', 'Egypt or North Africa', 'Another Arab country', 'Outside the Arab world'],
         'ar': ['لبنان', 'سوريا أو الأردن أو فلسطين', 'الخليج', 'مصر أو شمال أفريقيا', 'بلد عربي آخر', 'خارج العالم العربي']}},
  {'code': 'Country_Now', 'type': 'mc', 'role': 'CORE sample rule',
   'q': {'en': 'Where do you live now?', 'ar': 'أين تعيش الآن؟'}, 'o': 'same:Country_GrewUp'},
  {'code': 'Moved_Since2022', 'type': 'mc', 'role': 'CORE sample rule',
   'q': {'en': 'Have you moved to another country since 2022?', 'ar': 'هل انتقلت للعيش في بلد آخر منذ عام 2022؟'},
   'o': {'en': ['Yes', 'No'], 'ar': ['نعم', 'لا']}},
 ]},
 {'id': 'ai', 'title': {'en': 'Your use of AI tools', 'ar': 'استخدامك لأدوات الذكاء الاصطناعي'}, 'items': [
  {'code': 'AI_Start', 'type': 'mc', 'role': 'tenure covariate',
   'q': {'en': 'When did you start using AI tools regularly (at least weekly)?', 'ar': 'متى بدأت باستخدام أدوات الذكاء الاصطناعي بانتظام (مرة أسبوعياً على الأقل)؟'},
   'o': {'en': ['2022 or earlier', '2023', '2024', '2025', '2026'], 'ar': ['2022 أو قبل ذلك', '2023', '2024', '2025', '2026']}},
  {'code': 'AI_Freq', 'type': 'mc', 'role': 'descriptive / X check',
   'q': {'en': 'How often do you use AI tools?', 'ar': 'كم مرة تستخدم أدوات الذكاء الاصطناعي؟'},
   'o': {'en': ['Once a week', 'A few days a week', 'Once a day', 'Several times a day'],
         'ar': ['مرة في الأسبوع', 'بضعة أيام في الأسبوع', 'مرة في اليوم', 'عدة مرات في اليوم']}},
  {'code': 'AI_TaskShare', 'type': 'mc', 'role': 'X (AI intensity component)',
   'q': {'en': 'How much of your work or study do you do with the help of AI?', 'ar': 'كم من عملك أو دراستك تنجزه بمساعدة الذكاء الاصطناعي؟'},
   'o': {'en': ['Very little', 'Some', 'About half', 'Most', 'Almost all'], 'ar': ['القليل جداً', 'بعضه', 'نحو النصف', 'معظمه', 'كله تقريباً']}},
  {'code': 'AI_Breadth', 'type': 'check', 'role': 'X (AI intensity component: count of ticks)',
   'q': {'en': 'What do you use AI for? (tick all that apply)', 'ar': 'فيمَ تستخدم الذكاء الاصطناعي؟ (اختر كل ما ينطبق)'},
   'o': {'en': ['Writing or editing', 'Coding', 'Searching for information', 'Translation', 'Studying', 'Emails and messages', 'Ideas', 'Personal advice'],
         'ar': ['الكتابة أو التحرير', 'البرمجة', 'البحث عن معلومات', 'الترجمة', 'الدراسة', 'البريد والرسائل', 'توليد الأفكار', 'نصائح شخصية']}},
  {'code': 'AI_Lang', 'type': 'mc', 'role': 'X (language routed through AI)',
   'q': {'en': 'In which language do you usually write to AI?', 'ar': 'بأي لغة تكتب للذكاء الاصطناعي عادةً؟'},
   'o': {'en': ['Always Arabic', 'Mostly Arabic', 'Both equally', 'Mostly English', 'Always English', 'Another language'],
         'ar': ['العربية دائماً', 'العربية غالباً', 'الاثنتان بالتساوي', 'الإنجليزية غالباً', 'الإنجليزية دائماً', 'لغة أخرى']}},
  {'code': 'AI_Content', 'type': 'mc', 'role': 'X (exposure channel: recognised AI-generated content)',
   'q': {'en': 'How often do you come across AI-generated content (videos, voice-overs, summaries in search results)?',
         'ar': 'كم تصادف محتوى مولّداً بالذكاء الاصطناعي (فيديوهات، تعليق صوتي، ملخّصات في نتائج البحث)؟'},
   'o': {'en': ['Never', 'Rarely', 'Sometimes', 'Often', 'Every day'],
         'ar': ['لا أصادفه', 'نادراً', 'أحياناً', 'كثيراً', 'يومياً']}},
  {'code': 'AI_ContentLang', 'type': 'mc', 'role': 'X (consumption-side language choice at an AI-created choice point)',
   'q': {'en': 'When the same content is available in AI-generated Arabic voice and in the original English, which do you usually choose?',
         'ar': 'عندما يتوفّر المحتوى نفسه بصوت عربي مولّد بالذكاء الاصطناعي وبالإنجليزية الأصلية، ماذا تختار عادةً؟'},
   'o': {'en': ['Always Arabic', 'Mostly Arabic', 'Depends on the topic', 'Mostly English', 'Always English'],
         'ar': ['العربية دائماً', 'العربية غالباً', 'بحسب الموضوع', 'الإنجليزية غالباً', 'الإنجليزية دائماً']}},
  {'code': 'Events', 'type': 'check', 'role': 'covariate (EventMove / EventOther); also defines stable work/study status for ArUse_WorkStudy: stable = none of started university, graduated, new job, and Role != Neither',
   'q': {'en': 'Since you started using AI regularly, did any of these also happen? (tick all that apply)', 'ar': 'منذ أن بدأت باستخدام الذكاء الاصطناعي بانتظام، هل حدث لك أيضاً أيٌّ مما يلي؟ (اختر كل ما ينطبق)'},
   'o': {'en': ['Started university', 'Graduated', 'New job', 'Started studying or working in English', 'Moved to another country', 'None of these'],
         'ar': ['بدأت الجامعة', 'تخرّجت', 'بدأت عملاً جديداً', 'بدأت الدراسة أو العمل بالإنجليزية', 'انتقلت إلى بلد آخر', 'لا شيء مما سبق']}},
  {'code': 'FushaPreAI', 'type': 'mc', 'role': 'filter for Abil_Register + covariate',
   'q': {'en': 'Before using AI, did you write in Fusha (assignments, exams, official letters)?', 'ar': 'قبل استخدامك للذكاء الاصطناعي، هل كنت تكتب بالفصحى (واجبات، امتحانات، رسائل رسمية)؟'},
   'o': {'en': ['Yes, regularly', 'Sometimes', 'No'], 'ar': ['نعم، بانتظام', 'أحياناً', 'لا']}},
 ]},
 {'id': 'cur', 'title': {'en': 'Your languages today', 'ar': 'لغاتك اليوم'}, 'items': [
  {'code': 'CurUse', 'type': 'grid', 'scale': 'curuse', 'role': 'RQ1 current level (descriptive; never a covariate)',
   'q': {'en': 'These days, which language do you mostly use for each of these?', 'ar': 'هذه الأيام، ما اللغة التي تستخدمها غالباً في كلٍّ مما يلي؟'},
   'help': {'en': 'Arabic means your dialect or Fusha.', 'ar': 'نقصد بالعربية: لهجتك أو الفصحى.'},
   'rows': [
    ('CurUse_WorkStudy', 'Work or studies', 'العمل أو الدراسة'),
    ('CurUse_Writing', 'Writing messages and posts', 'كتابة الرسائل والمنشورات'),
    ('CurUse_Self', 'Talking to myself or writing my own notes', 'التحدث مع نفسي أو كتابة ملاحظاتي الخاصة'),
    ('CurUse_Personal', 'Personal matters', 'الأمور الشخصية'),
    ('CurUse_Family', 'With my family or friends', 'مع العائلة أو الأصدقاء'),
    ('CurUse_Religion', 'Religious texts', 'النصوص الدينية'),
    ('CurUse_Formal', 'Reading or writing formal texts (news, documents, articles)', 'قراءة أو كتابة نصوص رسمية (أخبار، وثائق، مقالات)'),
    ('CurUse_Consume', 'Following content (videos, articles)', 'متابعة المحتوى (فيديوهات، مقالات)'),
   ]},
 ]},
 {'id': 'change', 'title': {'en': 'Has AI changed your Arabic?', 'ar': 'هل غيّر الذكاء الاصطناعي عربيتك؟'}, 'items': [
  {'code': None, 'type': 'text',
   'help': {'en': "On this page we ask whether AI has changed how you use Arabic.\n• Compare now with before you started using AI regularly.\n• Mixing Arabic and English is normal.",
            'ar': 'في هذه الصفحة نسألك: هل غيّر الذكاء الاصطناعي طريقة استخدامك للعربية؟\n• قارن بين الآن وما قبل استخدامك المنتظم للذكاء الاصطناعي.\n• خلط العربية بالإنجليزية أمر طبيعي.'}},
  {'code': 'ArUse', 'type': 'grid', 'scale': 'change', 'role': 'Displacement (ArUse_*), Switching (Switch_Mode)',
   'q': {'en': 'Because of AI, do you now do each of these less or more?', 'ar': 'بسبب الذكاء الاصطناعي، هل أصبحت تقوم بكلٍّ مما يلي أقل أم أكثر؟'},
   'help': 'nochange',
   'rows': [
    ('ArUse_WorkStudy', 'Using Arabic in my work or studies', 'استخدام العربية في عملي أو دراستي', 'M'),
    ('ArUse_Writing', 'Writing messages or posts in Arabic', 'كتابة الرسائل أو المنشورات بالعربية', 'M'),
    ('ArUse_Self', 'Using Arabic when I talk to myself or write my own notes', 'استخدام العربية عندما أحدّث نفسي أو أكتب ملاحظاتي الخاصة', 'L'),
    ('ArUse_Personal', 'Using Arabic for personal matters', 'استخدام العربية في الحديث عن أموري الشخصية', 'L'),
    ('ArUse_Family', 'Using Arabic with my family or friends', 'استخدام العربية مع عائلتي أو أصدقائي', 'L'),
    ('ArUse_Fusha', 'Reading or writing Fusha (news, documents, articles)', 'قراءة الفصحى أو كتابتها (أخبار، وثائق، مقالات)', 'H'),
    ('ArUse_Religion', 'Reading or listening to religious texts', 'قراءة نصوص دينية أو الاستماع إليها', 'H'),
    ('ArUse_Consume', 'Following content in Arabic (videos, articles)', 'متابعة محتوى بالعربية (فيديوهات، مقالات)', 'M'),
    ('Switch_Mode', 'Switching between Arabic and English while working or studying', 'التنقّل بين العربية والإنجليزية أثناء العمل أو الدراسة', 'M'),
   ]},
  {'code': 'SwitchEng', 'type': 'mc', 'role': 'HEADLINE: self-reported AI-driven substitution where Arabic was available',
   'q': {'en': 'Has it happened that you did something in English, although you could have done it in Arabic, because AI helps you better in English?',
         'ar': 'هل حدث أن أنجزت عملاً بالإنجليزية، مع أنه كان بإمكانك إنجازه بالعربية، لأن الذكاء الاصطناعي يساعدك أفضل بالإنجليزية؟'},
   'o': {'en': ['Never', 'Once or twice', 'Sometimes', 'Often', 'Most of the time'],
         'ar': ['لم يحدث', 'مرة أو مرتين', 'أحياناً', 'كثيراً', 'في معظم الأحيان']}},
  {'code': 'SocialMedia', 'type': 'mc', 'scale': 'change', 'role': 'RIVAL DRIVER: same window and scale as ArUse, so AI-attributed change can be compared within person',
   'q': {'en': 'Over the same period, because of social media, do you now use Arabic less or more?',
         'ar': 'خلال الفترة نفسها، بسبب وسائل التواصل الاجتماعي، هل أصبحت تستخدم العربية أقل أم أكثر؟'}},
  {'code': 'Abil', 'type': 'grid', 'scale': 'easier', 'role': 'AbilityDecline (Abil_Register analysed only if FushaPreAI != No)',
   'q': {'en': 'Because of AI, has each of these become harder or easier for you, when you use Arabic on your own without AI?',
         'ar': 'بسبب الذكاء الاصطناعي، هل أصبح كلٌّ مما يلي أصعب أم أسهل عليك، عندما تستخدم العربية بنفسك من دون مساعدته؟'},
   'help': 'nochange',
   'rows': [
    ('Abil_Lexical', 'Finding the everyday Arabic word I need', 'تذكّر الكلمة العربية اليومية التي أحتاجها', 'L'),
    ('Abil_Fluency', 'Speaking my dialect smoothly, without pausing for words', 'التحدث بلهجتي بطلاقة دون التوقف بحثاً عن الكلمات', 'L'),
    ('Abil_ArabicOnly', 'Saying what I mean fully in Arabic, without English words', 'التعبير عمّا أريده بالعربية كاملاً دون كلمات إنجليزية', 'M'),
    ('Abil_Register', 'Writing a formal text in Fusha (e.g. a letter or report)', 'كتابة نص رسمي بالفصحى (مثل رسالة أو تقرير)', 'H'),
   ]},
 ]},
 {'id': 'views', 'title': {'en': 'Your views and language background', 'ar': 'رأيك وخلفيتك اللغوية'}, 'items': [
  {'code': 'Future', 'type': 'grid', 'scale': 'future', 'role': 'EXPLORATORY: expected encroachment into domains Arabic still holds',
   'q': {'en': 'In two years, do you think you will use Arabic more or less than you do today for each of these?',
         'ar': 'برأيك، بعد سنتين، هل ستستخدم العربية في كلٍّ مما يلي أكثر أم أقل مما تستخدمها اليوم؟'},
   'rows': [
    ('Future_WorkStudy', 'Work or studies', 'العمل أو الدراسة', 'M'),
    ('Future_Writing', 'Writing messages and posts', 'كتابة الرسائل والمنشورات', 'M'),
    ('Future_Self', 'Talking to myself or writing my own notes', 'التحدث مع نفسي أو كتابة ملاحظاتي الخاصة', 'L'),
    ('Future_Personal', 'Personal matters', 'الأمور الشخصية', 'L'),
    ('Future_Family', 'With my family or friends', 'مع العائلة أو الأصدقاء', 'L'),
    ('Future_Formal', 'Reading or writing formal texts', 'قراءة أو كتابة نصوص رسمية', 'H'),
    ('Future_Religion', 'Religious texts', 'النصوص الدينية', 'H'),
    ('Future_Consume', 'Following content (videos, articles)', 'متابعة المحتوى (فيديوهات، مقالات)', 'M'),
   ]},
  {'code': 'Gap', 'type': 'grid', 'scale': 'agree', 'role': 'X Perceived quality gap',
   'q': {'en': 'How much do you agree?', 'ar': 'إلى أي حد توافق على ما يلي؟'},
   'help': {'en': 'If you rarely use AI in Arabic, answer from your impression.', 'ar': 'إذا كنت نادراً ما تستخدم الذكاء الاصطناعي بالعربية، فأجب بحسب انطباعك.'},
   'rows': [
    ('Gap_Understand', 'AI understands me better in English than in Arabic', 'يفهمني الذكاء الاصطناعي بالإنجليزية أفضل من العربية', '-'),
    ('Gap_Accuracy', 'AI gives less accurate answers in Arabic than in English', 'يعطي الذكاء الاصطناعي إجابات أقل دقة بالعربية منها بالإنجليزية', '-'),
    ('Gap_Voice', 'AI-generated Arabic voices and videos sound less natural than English ones', 'الأصوات والفيديوهات العربية المولّدة بالذكاء الاصطناعي أقل طبيعية من الإنجليزية', '-'),
    ('Gap_Equal', 'AI answers in Arabic are as good as in English (reverse-coded)', 'إجابات الذكاء الاصطناعي بالعربية جيدة مثل إجاباته بالإنجليزية', 'R'),
   ]},
  {'code': 'L1_Home', 'type': 'check', 'role': 'eligibility check',
   'q': {'en': 'Languages spoken at home when you were a child (tick all)', 'ar': 'اللغات التي كنت تتحدثها في البيت في طفولتك (اختر كل ما ينطبق)'},
   'o': {'en': ['Arabic', 'English', 'French', 'Other'], 'ar': ['العربية', 'الإنجليزية', 'الفرنسية', 'غير ذلك']}},
  {'code': 'Sch_SciLang', 'type': 'mc', 'role': 'Medium covariate (rival explanation)',
   'q': {'en': 'At school, you studied science and maths mostly in…', 'ar': 'في المدرسة، درست العلوم والرياضيات غالباً باللغة…'},
   'o': {'en': ['Arabic', 'English', 'French', 'Other'], 'ar': ['العربية', 'الإنجليزية', 'الفرنسية', 'غير ذلك']}},
  {'code': 'Uni_Lang', 'type': 'mc', 'role': 'Medium covariate (rival explanation)',
   'q': {'en': 'At university, your courses were mostly in…', 'ar': 'في الجامعة، كانت مقرراتك غالباً باللغة…'},
   'o': {'en': ['Arabic', 'English', 'French', 'Mixed', 'I did not go to university'], 'ar': ['العربية', 'الإنجليزية', 'الفرنسية', 'مختلطة', 'لم ألتحق بالجامعة']}},
  {'code': 'Eng_Prof', 'type': 'mc', 'role': 'sensitivity covariate / ML',
   'q': {'en': 'Your English level', 'ar': 'مستواك في الإنجليزية'},
   'o': {'en': ['Weak', 'Average', 'Good', 'Very good', 'Excellent'], 'ar': ['ضعيف', 'متوسط', 'جيد', 'جيد جداً', 'ممتاز']}},
  {'code': 'Open', 'type': 'para', 'role': '1-3 illustrative quotes only',
   'q': {'en': 'Anything else about how AI has affected your Arabic? (optional)', 'ar': 'هل تودّ إضافة أي شيء عن تأثير الذكاء الاصطناعي على عربيتك؟ (اختياري)'},
   'help': {'en': "Please don't mention names of people or places of work.", 'ar': 'يُرجى عدم ذكر أسماء أشخاص أو أماكن عمل.'}},
 ]},
]
