* ==============================================================================.
* 01_import_and_score.sps -- GENERATED by analysis/prepare_data.py. Edit the .py, not this file.
* Imports coded.csv, labels it, flags exclusions, computes every score, saves the .sav.
* Before running: set the folder in FILE HANDLE below. Run all (Ctrl+A, then Run).
* ==============================================================================.

FILE HANDLE proj /NAME='C:\Users\User\ai-language-gap-paper\analysis'.

GET DATA /TYPE=TXT
  /FILE='proj/data/coded.csv'
  /ENCODING='UTF8' /DELCASE=LINE /DELIMITERS="," /QUALIFIER='"' /ARRANGEMENT=DELIMITED /FIRSTCASE=2
  /VARIABLES=
    id F3.0
    Consent F3.0
    Eligible F3.0
    Role F3.0
    Education F3.0
    Field F3.0
    Age F3.0
    Gender F3.0
    Country_GrewUp F3.0
    Country_Now F3.0
    Moved_Since2022 F3.0
    AI_Start F3.0
    AI_Freq F3.0
    AI_TaskShare F3.0
    AI_Breadth_1 F3.0
    AI_Breadth_2 F3.0
    AI_Breadth_3 F3.0
    AI_Breadth_4 F3.0
    AI_Breadth_5 F3.0
    AI_Breadth_6 F3.0
    AI_Breadth_7 F3.0
    AI_Breadth_8 F3.0
    AI_Lang F3.0
    AI_Content F3.0
    AI_ContentLang F3.0
    Events_1 F3.0
    Events_2 F3.0
    Events_3 F3.0
    Events_4 F3.0
    Events_5 F3.0
    Events_6 F3.0
    FushaPreAI F3.0
    CurUse_WorkStudy F3.0
    CurUse_Writing F3.0
    CurUse_Self F3.0
    CurUse_Personal F3.0
    CurUse_Family F3.0
    CurUse_Religion F3.0
    CurUse_Formal F3.0
    CurUse_Consume F3.0
    ArUse_WorkStudy F3.0
    ArUse_Writing F3.0
    ArUse_Self F3.0
    ArUse_Personal F3.0
    ArUse_Family F3.0
    ArUse_Fusha F3.0
    ArUse_Religion F3.0
    ArUse_Consume F3.0
    Switch_Mode F3.0
    SwitchEng F3.0
    SocialMedia F3.0
    Abil_Lexical F3.0
    Abil_Fluency F3.0
    Abil_ArabicOnly F3.0
    Abil_Register F3.0
    Future_WorkStudy F3.0
    Future_Writing F3.0
    Future_Self F3.0
    Future_Personal F3.0
    Future_Family F3.0
    Future_Formal F3.0
    Future_Religion F3.0
    Future_Consume F3.0
    Gap_Understand F3.0
    Gap_Accuracy F3.0
    Gap_Voice F3.0
    Gap_Equal F3.0
    L1_Home_1 F3.0
    L1_Home_2 F3.0
    L1_Home_3 F3.0
    L1_Home_4 F3.0
    Sch_SciLang F3.0
    Uni_Lang F3.0
    Eng_Prof F3.0
.

VARIABLE LABELS
  id "Respondent number (order of submission)"
  /Consent "I am 18 or older and I agree to take part."
  /Eligible "Do ALL of these apply to you?; Arabic is your first language; You also use English for study or work; You have used AI tools (such as ChatGPT, Gemini or Claude) at least weekly for 6 months or more"
  /Role "You are currently…"
  /Education "Education level (completed or in progress)"
  /Field "Field of study or work"
  /Age "Age"
  /Gender "Gender"
  /Country_GrewUp "Where did you grow up?"
  /Country_Now "Where do you live now?"
  /Moved_Since2022 "Have you moved to another country since 2022?"
  /AI_Start "When did you start using AI tools regularly (at least weekly)?"
  /AI_Freq "How often do you use AI tools?"
  /AI_TaskShare "How much of your work or study do you do with the help of AI?"
  /AI_Breadth_1 "What do you use AI for? (tick all that apply): Writing or editing"
  /AI_Breadth_2 "What do you use AI for? (tick all that apply): Coding"
  /AI_Breadth_3 "What do you use AI for? (tick all that apply): Searching for information"
  /AI_Breadth_4 "What do you use AI for? (tick all that apply): Translation"
  /AI_Breadth_5 "What do you use AI for? (tick all that apply): Studying"
  /AI_Breadth_6 "What do you use AI for? (tick all that apply): Emails and messages"
  /AI_Breadth_7 "What do you use AI for? (tick all that apply): Ideas"
  /AI_Breadth_8 "What do you use AI for? (tick all that apply): Personal advice"
  /AI_Lang "In which language do you usually write to AI?"
  /AI_Content "How often do you come across AI-generated content (videos, voice-overs, summaries in search results)?"
  /AI_ContentLang "When the same content is available in AI-generated Arabic voice and in the original English, which do you usually choose?"
  /Events_1 "Since you started using AI regularly, did any of these also happen? (tick all that apply): Started university"
  /Events_2 "Since you started using AI regularly, did any of these also happen? (tick all that apply): Graduated"
  /Events_3 "Since you started using AI regularly, did any of these also happen? (tick all that apply): New job"
  /Events_4 "Since you started using AI regularly, did any of these also happen? (tick all that apply): Started studying or working in English"
  /Events_5 "Since you started using AI regularly, did any of these also happen? (tick all that apply): Moved to another country"
  /Events_6 "Since you started using AI regularly, did any of these also happen? (tick all that apply): None of these"
  /FushaPreAI "Before using AI, did you write in Fusha (assignments, exams, official letters)?"
  /CurUse_WorkStudy "Language today: Work or studies"
  /CurUse_Writing "Language today: Writing messages and posts"
  /CurUse_Self "Language today: Talking to myself or writing my own notes"
  /CurUse_Personal "Language today: Personal matters"
  /CurUse_Family "Language today: With my family or friends"
  /CurUse_Religion "Language today: Religious texts"
  /CurUse_Formal "Language today: Reading or writing formal texts (news, documents, articles)"
  /CurUse_Consume "Language today: Following content (videos, articles)"
  /ArUse_WorkStudy "Because of AI, less or more: Using Arabic in my work or studies"
  /ArUse_Writing "Because of AI, less or more: Writing messages or posts in Arabic"
  /ArUse_Self "Because of AI, less or more: Using Arabic when I talk to myself or write my own notes"
  /ArUse_Personal "Because of AI, less or more: Using Arabic for personal matters"
  /ArUse_Family "Because of AI, less or more: Using Arabic with my family or friends"
  /ArUse_Fusha "Because of AI, less or more: Reading or writing Fusha (news, documents, articles)"
  /ArUse_Religion "Because of AI, less or more: Reading or listening to religious texts"
  /ArUse_Consume "Because of AI, less or more: Following content in Arabic (videos, articles)"
  /Switch_Mode "Because of AI, less or more: Switching between Arabic and English while working or studying"
  /SwitchEng "Has it happened that you did something in English, although you could have done it in Arabic, because AI helps you better in English?"
  /SocialMedia "Over the same period, because of social media, do you now use Arabic less or more?"
  /Abil_Lexical "Without AI, harder or easier: Finding the everyday Arabic word I need"
  /Abil_Fluency "Without AI, harder or easier: Speaking my dialect smoothly, without pausing for words"
  /Abil_ArabicOnly "Without AI, harder or easier: Saying what I mean fully in Arabic, without English words"
  /Abil_Register "Without AI, harder or easier: Writing a formal text in Fusha (e.g. a letter or report)"
  /Future_WorkStudy "In two years, Arabic more or less: Work or studies"
  /Future_Writing "In two years, Arabic more or less: Writing messages and posts"
  /Future_Self "In two years, Arabic more or less: Talking to myself or writing my own notes"
  /Future_Personal "In two years, Arabic more or less: Personal matters"
  /Future_Family "In two years, Arabic more or less: With my family or friends"
  /Future_Formal "In two years, Arabic more or less: Reading or writing formal texts"
  /Future_Religion "In two years, Arabic more or less: Religious texts"
  /Future_Consume "In two years, Arabic more or less: Following content (videos, articles)"
  /Gap_Understand "Agree: AI understands me better in English than in Arabic"
  /Gap_Accuracy "Agree: AI gives less accurate answers in Arabic than in English"
  /Gap_Voice "Agree: AI-generated Arabic voices and videos sound less natural than English ones"
  /Gap_Equal "Agree: AI answers in Arabic are as good as in English (stored as answered; Gap_Equal_r is reversed)"
  /L1_Home_1 "Languages spoken at home when you were a child (tick all): Arabic"
  /L1_Home_2 "Languages spoken at home when you were a child (tick all): English"
  /L1_Home_3 "Languages spoken at home when you were a child (tick all): French"
  /L1_Home_4 "Languages spoken at home when you were a child (tick all): Other"
  /Sch_SciLang "At school, you studied science and maths mostly in…"
  /Uni_Lang "At university, your courses were mostly in…"
  /Eng_Prof "Your English level"
.

VALUE LABELS
  Consent 1 "I agree" 0 "I do not agree"
  /Eligible 1 "Yes" 0 "No"
  /Role 1 "A student" 2 "Employed" 3 "Both" 4 "Other"
  /Education 1 "Secondary" 2 "Bachelor's" 3 "Master's or higher"
  /Field 1 "Computing / IT" 2 "Engineering" 3 "Sciences or health" 4 "Business" 5 "Humanities, education or law" 6 "Other"
  /Age 1 "Under 25" 2 "25 to 34" 3 "35 to 44" 4 "45 or over"
  /Gender 1 "Female" 2 "Male" 3 "Prefer not to say"
  /Country_GrewUp 1 "Lebanon" 2 "Syria, Jordan or Palestine" 3 "The Gulf" 4 "Egypt or North Africa" 5 "Another Arab country" 6 "Outside the Arab world"
  /Country_Now 1 "Lebanon" 2 "Syria, Jordan or Palestine" 3 "The Gulf" 4 "Egypt or North Africa" 5 "Another Arab country" 6 "Outside the Arab world"
  /Moved_Since2022 1 "Yes" 2 "No"
  /AI_Start 1 "2022 or earlier" 2 "2023" 3 "2024" 4 "2025" 5 "2026"
  /AI_Freq 1 "Once a week" 2 "A few days a week" 3 "Once a day" 4 "Several times a day"
  /AI_TaskShare 1 "Very little" 2 "Some" 3 "About half" 4 "Most" 5 "Almost all"
  /AI_Breadth_1 0 "Not ticked" 1 "Ticked"
  /AI_Breadth_2 0 "Not ticked" 1 "Ticked"
  /AI_Breadth_3 0 "Not ticked" 1 "Ticked"
  /AI_Breadth_4 0 "Not ticked" 1 "Ticked"
  /AI_Breadth_5 0 "Not ticked" 1 "Ticked"
  /AI_Breadth_6 0 "Not ticked" 1 "Ticked"
  /AI_Breadth_7 0 "Not ticked" 1 "Ticked"
  /AI_Breadth_8 0 "Not ticked" 1 "Ticked"
  /AI_Lang 1 "Always Arabic" 2 "Mostly Arabic" 3 "Both equally" 4 "Mostly English" 5 "Always English" 6 "Another language"
  /AI_Content 1 "Never" 2 "Rarely" 3 "Sometimes" 4 "Often" 5 "Every day"
  /AI_ContentLang 1 "Always Arabic" 2 "Mostly Arabic" 3 "Depends on the topic" 4 "Mostly English" 5 "Always English"
  /Events_1 0 "Not ticked" 1 "Ticked"
  /Events_2 0 "Not ticked" 1 "Ticked"
  /Events_3 0 "Not ticked" 1 "Ticked"
  /Events_4 0 "Not ticked" 1 "Ticked"
  /Events_5 0 "Not ticked" 1 "Ticked"
  /Events_6 0 "Not ticked" 1 "Ticked"
  /FushaPreAI 1 "Yes, regularly" 2 "Sometimes" 3 "No"
  /CurUse_WorkStudy 1 "Mostly Arabic" 2 "Arabic and English" 3 "Mostly English" 4 "Another language" 5 "Not applicable"
  /CurUse_Writing 1 "Mostly Arabic" 2 "Arabic and English" 3 "Mostly English" 4 "Another language" 5 "Not applicable"
  /CurUse_Self 1 "Mostly Arabic" 2 "Arabic and English" 3 "Mostly English" 4 "Another language" 5 "Not applicable"
  /CurUse_Personal 1 "Mostly Arabic" 2 "Arabic and English" 3 "Mostly English" 4 "Another language" 5 "Not applicable"
  /CurUse_Family 1 "Mostly Arabic" 2 "Arabic and English" 3 "Mostly English" 4 "Another language" 5 "Not applicable"
  /CurUse_Religion 1 "Mostly Arabic" 2 "Arabic and English" 3 "Mostly English" 4 "Another language" 5 "Not applicable"
  /CurUse_Formal 1 "Mostly Arabic" 2 "Arabic and English" 3 "Mostly English" 4 "Another language" 5 "Not applicable"
  /CurUse_Consume 1 "Mostly Arabic" 2 "Arabic and English" 3 "Mostly English" 4 "Another language" 5 "Not applicable"
  /ArUse_WorkStudy -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /ArUse_Writing -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /ArUse_Self -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /ArUse_Personal -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /ArUse_Family -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /ArUse_Fusha -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /ArUse_Religion -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /ArUse_Consume -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /Switch_Mode -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /SwitchEng 1 "Never" 2 "Once or twice" 3 "Sometimes" 4 "Often" 5 "Most of the time"
  /SocialMedia -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more"
  /Abil_Lexical -2 "Much harder" -1 "Harder" 0 "No change" 1 "Easier" 2 "Much easier"
  /Abil_Fluency -2 "Much harder" -1 "Harder" 0 "No change" 1 "Easier" 2 "Much easier"
  /Abil_ArabicOnly -2 "Much harder" -1 "Harder" 0 "No change" 1 "Easier" 2 "Much easier"
  /Abil_Register -2 "Much harder" -1 "Harder" 0 "No change" 1 "Easier" 2 "Much easier"
  /Future_WorkStudy -2 "Much less" -1 "Less" 0 "The same as now" 1 "More" 2 "Much more"
  /Future_Writing -2 "Much less" -1 "Less" 0 "The same as now" 1 "More" 2 "Much more"
  /Future_Self -2 "Much less" -1 "Less" 0 "The same as now" 1 "More" 2 "Much more"
  /Future_Personal -2 "Much less" -1 "Less" 0 "The same as now" 1 "More" 2 "Much more"
  /Future_Family -2 "Much less" -1 "Less" 0 "The same as now" 1 "More" 2 "Much more"
  /Future_Formal -2 "Much less" -1 "Less" 0 "The same as now" 1 "More" 2 "Much more"
  /Future_Religion -2 "Much less" -1 "Less" 0 "The same as now" 1 "More" 2 "Much more"
  /Future_Consume -2 "Much less" -1 "Less" 0 "The same as now" 1 "More" 2 "Much more"
  /Gap_Understand 1 "Strongly disagree" 2 "Disagree" 3 "Neutral" 4 "Agree" 5 "Strongly agree"
  /Gap_Accuracy 1 "Strongly disagree" 2 "Disagree" 3 "Neutral" 4 "Agree" 5 "Strongly agree"
  /Gap_Voice 1 "Strongly disagree" 2 "Disagree" 3 "Neutral" 4 "Agree" 5 "Strongly agree"
  /Gap_Equal 1 "Strongly disagree" 2 "Disagree" 3 "Neutral" 4 "Agree" 5 "Strongly agree"
  /L1_Home_1 0 "Not ticked" 1 "Ticked"
  /L1_Home_2 0 "Not ticked" 1 "Ticked"
  /L1_Home_3 0 "Not ticked" 1 "Ticked"
  /L1_Home_4 0 "Not ticked" 1 "Ticked"
  /Sch_SciLang 1 "Arabic" 2 "English" 3 "French" 4 "Other"
  /Uni_Lang 1 "Arabic" 2 "English" 3 "French" 4 "Mixed" 5 "I did not go to university"
  /Eng_Prof 1 "Weak" 2 "Average" 3 "Good" 4 "Very good" 5 "Excellent"
.

MISSING VALUES AI_Lang (6).
MISSING VALUES CurUse_WorkStudy (4,5).
MISSING VALUES CurUse_Writing (4,5).
MISSING VALUES CurUse_Self (4,5).
MISSING VALUES CurUse_Personal (4,5).
MISSING VALUES CurUse_Family (4,5).
MISSING VALUES CurUse_Religion (4,5).
MISSING VALUES CurUse_Formal (4,5).
MISSING VALUES CurUse_Consume (4,5).

* ---------------------------------------------------------------- flags (plan 6.2 and 7.0).
COMPUTE excl_region = (Country_GrewUp = 6 OR Country_Now = 6).
COMPUTE moved = (Moved_Since2022 = 1 OR Events_5 = 1).
* core: the plan's core sample (sensitivity) - grew up and lives in the Arab region, no move since 2022.
* The primary analysis uses all respondents (decision of 3 Oct 2026, ANALYSIS-DECISIONS.md).
COMPUTE core = (excl_region = 0 AND moved = 0).
* stable: same workplace or university throughout the AI period (no new university, graduation or job; role not "other").
COMPUTE stable = (Events_1 = 0 AND Events_2 = 0 AND Events_3 = 0 AND Role <> 4).
* straightline: every change row "much less" or every row "much more" (plan 7.0.5; sensitivity only).
COMPUTE straightline = (MAX(ArUse_WorkStudy, ArUse_Writing, ArUse_Self, ArUse_Personal, ArUse_Family, ArUse_Fusha, ArUse_Religion, ArUse_Consume, Switch_Mode) = -2 OR MIN(ArUse_WorkStudy, ArUse_Writing, ArUse_Self, ArUse_Personal, ArUse_Family, ArUse_Fusha, ArUse_Religion, ArUse_Consume, Switch_Mode) = 2).

* ---------------------------------------------------------------- domain change, filtered.
* A domain that does not apply (Language today = 5, not applicable) is set to missing.
* So "does not do this" is not counted as "AI changed nothing".
* VALUE() is needed: 5 is declared user-missing, and a plain comparison with it would never be true.
DO REPEAT a = ArUse_WorkStudy ArUse_Writing ArUse_Self ArUse_Personal ArUse_Family ArUse_Fusha ArUse_Religion ArUse_Consume
         /c = CurUse_WorkStudy CurUse_Writing CurUse_Self CurUse_Personal CurUse_Family CurUse_Formal CurUse_Religion CurUse_Consume
         /f = d_WorkStudy d_Writing d_Self d_Personal d_Family d_Fusha d_Religion d_Consume.
  COMPUTE f = a.
  IF (VALUE(c) = 5) f = $SYSMIS.
END REPEAT.

* ---------------------------------------------------------------- scores.
* Loss and decline scores: HIGHER = MORE LOSS (plan 7.1). d_X stay raw change (negative = less Arabic).
* Suffix 4 or 3 = sensitivity variant; the unsuffixed score is the primary one (see ANALYSIS-DECISIONS.md).
COMPUTE DomainsValid = NVALID(d_WorkStudy, d_Writing, d_Self, d_Personal, d_Family, d_Fusha, d_Religion, d_Consume).
COMPUTE Displacement = -MEAN.6(d_WorkStudy, d_Writing, d_Self, d_Personal, d_Family, d_Fusha, d_Religion, d_Consume).
COMPUTE Displacement4 = -MEAN.3(d_Writing, d_Self, d_Personal, d_Family).
COMPUTE NetLoss = (Displacement > 0).
COMPUTE Disp_Fusha = -d_Fusha.
COMPUTE Disp_WorkStudy = -d_WorkStudy.
COMPUTE Disp_Personal = -d_Personal.
COMPUTE Disp_Family = -d_Family.
COMPUTE DialectLoss = -MEAN(d_Self, d_Personal, d_Family).
COUNT DomainsLost = d_WorkStudy d_Writing d_Self d_Personal d_Family d_Fusha d_Religion d_Consume (LO THRU -1).
COMPUTE FormalLoss = -MEAN(d_WorkStudy, d_Fusha).
COMPUTE AnyFormalLoss = (MIN(d_WorkStudy, d_Fusha) <= -1).
* Fusha writing ability only counts for people who wrote Fusha before AI (FushaPreAI 3 = No).
COMPUTE Abil_Register_f = Abil_Register.
IF (FushaPreAI = 3) Abil_Register_f = $SYSMIS.
COMPUTE AbilityDecline = -MEAN.2(Abil_Lexical, Abil_Fluency, Abil_ArabicOnly).
COMPUTE AbilityDecline4 = -MEAN.3(Abil_Lexical, Abil_Fluency, Abil_ArabicOnly, Abil_Register_f).
COMPUTE Gap_Equal_r = 6 - Gap_Equal.
COMPUTE QualityGap = MEAN.3(Gap_Understand, Gap_Accuracy, Gap_Voice, Gap_Equal_r).
COMPUTE QualityGap3 = MEAN(Gap_Understand, Gap_Accuracy, Gap_Equal_r).
COMPUTE Expected = MEAN.6(Future_WorkStudy, Future_Writing, Future_Self, Future_Personal, Future_Family, Future_Formal, Future_Religion, Future_Consume).
COMPUTE AI_BreadthCount = SUM(AI_Breadth_1, AI_Breadth_2, AI_Breadth_3, AI_Breadth_4, AI_Breadth_5, AI_Breadth_6, AI_Breadth_7, AI_Breadth_8).
COMPUTE EnglishShare = AI_Lang.
COMPUTE AI_TenureRank = 6 - AI_Start.
COMPUTE SwitchEng_bin = (SwitchEng >= 3).
COMPUTE Age25 = (Age >= 2).
COMPUTE Computing = (Field = 1).
COMPUTE EventMove = (Events_4 = 1 OR Events_5 = 1).
COMPUTE Medium = (ANY(Sch_SciLang, 2, 3) OR ANY(Uni_Lang, 2, 3, 4)).
DESCRIPTIVES AI_Freq AI_TaskShare AI_BreadthCount /SAVE.
* AI intensity = mean of z(task share) and z(breadth). Frequency is descriptive only, as planned.
COMPUTE AI_Intensity = MEAN(ZAI_TaskShare, ZAI_BreadthCount).
COMPUTE AI_Intensity3 = MEAN(ZAI_Freq, ZAI_TaskShare, ZAI_BreadthCount).
EXECUTE.

VARIABLE LABELS
  excl_region "Grew up or lives outside the Arab world"
  /moved "Moved country since 2022 or since starting AI"
  /core "Core sample (sensitivity): grew up and lives in the Arab region, no move since 2022"
  /stable "Same workplace or university throughout the AI period"
  /straightline "Every change row much less, or every row much more"
  /DomainsValid "Number of domains that apply"
  /Displacement "Displacement: minus mean AI-attributed change over the domains that apply (6+ of 8); higher = more loss"
  /Displacement4 "Displacement over writing, self, personal, family only (sensitivity); higher = more loss"
  /NetLoss "Net loss: Displacement above 0"
  /Disp_Fusha "Loss in Fusha (minus change); higher = more loss"
  /Disp_WorkStudy "Loss in work or study (minus change); higher = more loss"
  /Disp_Personal "Loss in personal matters (minus change); higher = more loss"
  /Disp_Family "Loss with family or friends (minus change); higher = more loss"
  /DialectLoss "Loss in the spoken-dialect domains: self, personal, family; higher = more loss"
  /DomainsLost "Number of domains with less Arabic because of AI (0-8)"
  /FormalLoss "Loss in the formal domains (the H1 domains): work/study, Fusha; higher = more loss"
  /AnyFormalLoss "Less Arabic in work/study or Fusha"
  /AbilityDecline "Ability decline without AI: lexical, fluency, Arabic only; higher = harder"
  /AbilityDecline4 "Ability decline incl. Fusha register item (sensitivity); higher = harder"
  /QualityGap "Perceived AI quality gap, Arabic vs English (4 items, 1..5, higher = bigger gap)"
  /QualityGap3 "Perceived quality gap without the AI-voice item (sensitivity)"
  /Expected "Expected change in Arabic use over two years (-2..+2, negative = less)"
  /AI_BreadthCount "Number of AI uses ticked (0-8)"
  /AI_Intensity "AI intensity: mean z of share of work and breadth"
  /AI_Intensity3 "AI intensity incl. frequency (sensitivity)"
  /EnglishShare "English share of AI use: 1 always Arabic .. 5 always English"
  /AI_TenureRank "AI tenure rank (5 = started 2022 or earlier)"
  /SwitchEng_bin "Substituted English for Arabic at least sometimes"
  /Age25 "Aged 25 or over"
  /Computing "Field: computing / IT"
  /EventMove "Moved country or started studying/working in English during the AI period"
  /Medium "Foreign-medium school science or university (English, French or mixed)"
  /Abil_Register_f "Without AI, writing formal Fusha: harder or easier; missing if no Fusha writing before AI"
  /Gap_Equal_r "Gap_Equal reversed (6 - answer): higher = AI worse in Arabic"
  /d_WorkStudy "AI-attributed change, WorkStudy; not applicable = missing; -2 much less .. +2 much more"
  /d_Writing "AI-attributed change, Writing; not applicable = missing; -2 much less .. +2 much more"
  /d_Self "AI-attributed change, Self; not applicable = missing; -2 much less .. +2 much more"
  /d_Personal "AI-attributed change, Personal; not applicable = missing; -2 much less .. +2 much more"
  /d_Family "AI-attributed change, Family; not applicable = missing; -2 much less .. +2 much more"
  /d_Fusha "AI-attributed change, Fusha; not applicable = missing; -2 much less .. +2 much more"
  /d_Religion "AI-attributed change, Religion; not applicable = missing; -2 much less .. +2 much more"
  /d_Consume "AI-attributed change, Consume; not applicable = missing; -2 much less .. +2 much more"
.
VALUE LABELS excl_region moved core stable straightline NetLoss AnyFormalLoss SwitchEng_bin Age25 Computing EventMove Medium 0 "No" 1 "Yes".
VALUE LABELS d_WorkStudy d_Writing d_Self d_Personal d_Family d_Fusha d_Religion d_Consume -2 "Much less" -1 "Less" 0 "No change" 1 "More" 2 "Much more".
VALUE LABELS Abil_Register_f -2 "Much harder" -1 "Harder" 0 "No change" 1 "Easier" 2 "Much easier".
VALUE LABELS Gap_Equal_r 1 "Strongly agree (as good)" 2 "Agree" 3 "Neutral" 4 "Disagree" 5 "Strongly disagree (not as good)".

* Reliability is computed in 02_hypotheses.sps, on the primary sample.

* ---------------------------------------------------------------- check against prepare_data.py output.
DESCRIPTIVES Displacement Displacement4 NetLoss DialectLoss DomainsLost FormalLoss AnyFormalLoss AbilityDecline
  AbilityDecline4 QualityGap QualityGap3 Expected AI_BreadthCount AI_Intensity AI_Intensity3 SwitchEng_bin /STATISTICS=MEAN STDDEV MIN MAX.
FREQUENCIES excl_region moved core stable straightline Age25 Computing EventMove Medium.

SAVE OUTFILE='proj/data/ai-arabic-survey.sav'.
